name: "Publish package and documentation"

on:
  release:
    types: ["published"]

jobs:
  packages:
    name: "Build and publish release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Build
        run: uv build

      - name: Publish RC packages to PyPI Test
        if: contains(github.event.release.tag_name, '-rc')
        run: |
          uv publish --index testpypi --token ${{ secrets.TEST_PYPI_TOKEN }}

      - name: Publish release packages to PyPI
        if: ${{ ! contains(github.event.release.tag_name, '-rc') }}
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}

  docs:
    needs: packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Generate docs
        run: make install generate-docs

      - name: Publish RC docs
        if: contains(github.event.release.tag_name, '-rc')
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          # this puts the docs for this tag under gh-pages:/rc/<tag>/
          destination_dir: rc/${{ github.event.release.tag_name }}

      - name: Publish release docs
        if: ${{ ! contains(github.event.release.tag_name, '-rc') }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
